# -*- coding: utf-8 -*-
"""MLBasic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoO3RYtFXpWSKD7N6xppn1QwK_Vy8Llk
"""

print ("Hello Machine Learning")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print ("All Libraries imported Successfully")
#Create Dataset
data = {
    "Experience": [1, 2, 3, 4, 5],
    "Salary": [30000, 35000, 40000, 45000, 50000],
    "Age": [25, 30, 35, 40, 50]
}

##DataFrame : 2-D table of Data
df = pd.DataFrame(data)
df.columns = ["Experience", "Salary", "Age"]
df
print("Information : ")
print(df.info())
print("Description : ")
print(df.describe())
print("Filter Age : ")
print(df[df["Age"] > 25])
print("Sorted by Salary : ")
print(df.sort_values(by="Salary", ascending=True))


##Graph
##scatter plot shows the relationship between two numerical values
##eg : (1,30000)
plt.scatter(df["Experience"], df["Salary"])
plt.xlabel("Experience (Years)")
plt.ylabel("Salary")
plt.title("Experience vs Salary")
plt.grid(True)
plt.show()